name: Lighthouse CI
on: pull_request
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    name: Measure Performance
    permissions:
      issues: write

    steps:
      - uses: actions/checkout@v2
      - name: Wait for vercel
        uses: patrickedqvist/wait-for-vercel-preview@v1.1.1
        id: vercel
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          max_timeout: 120
      
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v8
        id: lighthouse
        with:
          urls: |
            ${{ steps.vercel.outputs.url }}
          temporaryPublicStorage: true
        env:
          LHCI_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Parse Lighthouse output
        run: |
          outputUrl=$( ${{ steps.lighthouse.links }} | jq '.${{ steps.vercel.outputs.URL }}' )
          echo "OUTPUT=$outputUrl" >> "$GITHUB_ENV"

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          body: |
           Check out the Lighthouse CI results:
            - $OUTPUT
            -
            - Created using [create-or-update-comment][1]

            [1]: https://github.com/peter-evans/create-or-update-comment
          

